### PR TITLE
Fix backward dragging for slideshows with only 2 slides

### PR DESCRIPTION
**Pull request by gradynoonen**
Not sure if this is the most elegant solution, but it fixes an issue with dragging a slide backwards in slideshows with only two items.

### CODE REVIEW

**Comment by keeganbrown** [comment]
This solution could cause a problem or two if there is necessary Javascript attached to the content of the slides, and has the potential to double any IDs that are on content within the slide (which could cause other problems). It's certainly a good solution for simple slideshows. I've got a few more fixes I want to merge up before I merge this in too. Thanks for helping!

**Comment by keeganbrown** [comment]
I just pushed up some fixes that should make backward dragging for slideshows with only 2 slides, without having to duplicate the slides. Please let me know if that solves the issue. Thanks!

**Comment by gradynoonen** [comment]
Yeah, I didn't think adding slides was ideal, but couldn't think of another solution that would happen instantaneously when the user starts dragging in a certain direction. How would the hidden slide know which direction to come from until after touchMove had already begun? Where did you push your fixes? I couldn't find anything regarding this issue in your last 2 commits.

**Comment by keeganbrown** [comment]
Sorry about my shabby commenting. I was in a rush last night. I added 4 IF statements, lines 1941, 1953, 1993, and 2005. The easiest place to add this fix was (unfortunately) in the transitions themselves. The IF statement looks like this: 
''' if ( diffPos.pageX \* dir.x > 0 || diffPos.pageY \* dir.y > 0 ) { '''
All that this statement does is to position the previous/next slide conditionally based on whether or not the touch moment is positive or negative. In doing so, we avoid having to duplicate the slides. The downside is that any other transitions made for touch will have to have similar logic built in. Fixing this issue makes me wonder if I shouldn't rework the format of the touch transitions to fall better in line with cycle's methodology.

**Comment by riverofjanuary** [comment]
Keegan
My sincere apologies for jumping on this pull request but I have not for the life of me found how to open an issue in GITHUB to comment on the Touch mods. First, thanks very much for working on this - but on my Android 2.3.4 I cannot get it to work. Even the slideshow itself doesn't show up (whereas it does, on other sites, in normal jqcycle). See the screenshot here: http://i.imgur.com/ScrJI.png . Looking forward to your response!

**Comment by gradynoonen** [comment]
Awesome! I'll give it a try when I get a chance and let you know what happens. I found another couple bugs that I attempted to fix, but I'm sure my fixes for those are not optimal either. Do you want me to add pull requests for those also, so you can check them out?

**Comment by keeganbrown** [comment]
@gradynoonen Yes please! 

@riverofjanuary I'm looking in to this now. Thanks for letting me know! I just added the issues tab, so you should be able to submit issues now. Sorry about that.

**Comment by keeganbrown** [comment]
@riverofjanuary ok andriod should be behaving again now. I've moved where the example pages live, so please use the new location when you test. Thanks!

**Comment by riverofjanuary** [comment]
@keeganbrown we are good! works great. So implementing this is just a matter of including the code and adding a few options to the existing slideshow code?

**Comment by gradynoonen** [comment]
Your fix seems to work beautifully. I'm closing this. I'll add my other two pull requests when I get a minute.

**Comment by keeganbrown** [comment]
@riverofjanuary yes -- just a couple extra options. I've only made three "touch transitions" so, unfortunately it's not a robust as the full set of regular cycle transition options.

@gradynoonen Thanks!

**Pull request closed without merging**
